### ISSUE TITLE
make your prompt use placeholder images

### ISSUE THREAD

**Issue by deletosh** [julianmonroy924/first-ecommerce-store#3]

**Comment by deletosh** [comment]
@deletosh i'm confused what do you mean....

**Comment by julianmonroy924** [comment]
@deletosh Not really sure what you mean by this?

**Comment by deletosh** [comment]
@julianmonroy924 when prototyping HTML pages, we'd often use placeholder service like placeholder.com. E.g. if I want an image that 200x200, I can do https://via.placeholder.com/200 which gives me:

![](https://via.placeholder.com/200)

You can include it in your prompt for GPT to use placeholder service for images (this prevents your page from looking broken)
